config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :users
resources :categories
resources :ingredients
resources :orders
resources :order_details

    root to: "users#index"
  end

  resources :orders
  post 'orders/opcion'
  post 'orders/PrimeraEtapa'
  root 'home#index'
  get '/stats' => 'stats#graph'

  devise_for :users
  #root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :hour, presence: true
  validates :quantity, presence: true
  validates :tamaño, presence: true
  validates :tipo, presence: true

  attr_accessor :ingredients, :pan, :queso
  validates :ingredients, presence: true
  validates :pan, presence: true
  validates :queso, presence: true


  after_create :save_ingredients

  def ingredients=(value)
  	@ingredients = value
  end

  def pan=(value)
    @pan = value
  end

  def queso=(value)
    @queso = value
  end


  def save_ingredients
  unless @ingredients.nil?
  	@ingredients.each do |ingrediente_id|
      precio = Ingredient.find(ingrediente_id).Price
  		OrderDetail.create(order_id: self.id, ingredient_id: ingrediente_id, price: precio)
  		#toca corregir price al precio where id_ingrediente = self.id
  	end
  end
    OrderDetail.create(order_id: self.id, ingredient_id: @pan, price: 0)
    OrderDetail.create(order_id: self.id, ingredient_id: @queso, price: 0)
    OrderDetail.create(order_id: self.id, ingredient_id: Order.find(self.id).tipo, price: 0)

    compra = Order.find(self.id)
    User.find(compra.user_id).update(saldo: (User.find(compra.user_id).saldo - compra.total))
  end
  
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_order_detail, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @ingredients = Ingredient.order(:category_id).all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @ingredients = Ingredient.order(:category_id).all
  end

  # GET /orders/1/edit
  def edit
  end

  def opcion
    @sizeSelected = params['myform']['opc']
    render 'orders/_tipos', sizeSelect: @sizeSelected
    
  end

  def PrimeraEtapa
    orden = Order.new
    @ingredients = Ingredient.order(:category_id).all
    begin
      @tipo = params['myform']['tipo']
      render 'orders/_form', :locals => {:order => orden, :tipo => @tipo}
    rescue Exception => e
      redirect_to new_order_path, alert: 'Ha ocurrido un error al guardar tu compra. Intenta de nuevo.'
    end

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.ingredients = params[:ingredients]
    @order.pan = params[:panSelected]
    @order.queso = params[:quesoSelected]
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Su orden fue creada correctamente.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to new_order_path, alert: 'Ha ocurrido un error al guardar tu compra. Intenta de nuevo.' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])

      rescue ActiveRecord::RecordNotFound
         redirect_to new_order_path, alert: 'Ha ocurrido un error al guardar tu compra. Intenta de nuevo.'
    end

    def set_order_detail
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:created_at, :hour, :comments, :user_id, :quantity, :total, :tipo, :tamaño, :ingredients, :panSelected, :quesoSelected)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<style>
      /* NOTE: The styles were added inline because Prefixfree needs access to your styles and they must be inlined if they are on local disk! */
body {
  font-family: "Open Sans", sans-serif;
  height: 100vh;  
}


.actions input {
  width: 30%;
  height: 100%;
  padding: 10px 10px;
  background: #201C3D;
  color: #fff;
  display: block;
  border: none;
  margin-top: 20px;
  left: 0;
  bottom: 0;
  max-height: 60px;
  border: 0px solid rgba(0, 0, 0, 0.1);
  border-radius: 0 0 2px 2px;
  transform: rotateZ(0deg);
  transition: all 0.1s ease-out;
  border-bottom-width: 7px;
  font-size:20px;
 
}

</style>  
<center>

<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <table width="1213" border="0" cellpadding="0" cellspacing="0">
        <tbody>
            <tr> <td width="155" scope="col">&nbsp;</td></tr>
            <tr> <td width="155" scope="col">&nbsp;</td></tr>
            <tr> <td width="155" scope="col">&nbsp;</td></tr>
             <tr>
              <td width="155" scope="col">&nbsp;</td>
              <td width="964" scope="col">
                  <div class="row" >
                  <center><h2 style="color:#201C3D;">PANES</h2></center>
                  <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %>
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==4) %>
                        <div class="col-md-3">
                        <center>
                        <h3><%= ingredient.name_Ingredient %></h3><br>
                        <center><img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>"/><br><center>
                        <center><input type="radio" name="panSelected" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados" ></center>
                        </div>
                    <% end %>
                  <% end %>
                </div>
                <center>
                <br><br>
              <div class="row" > 
                <center><h2 style="color:#201C3D;">Quesos</h2></center>
                <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %> 
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==5) %>
                        <div class="col-md-3">
                         <center>
                         <h3><%= ingredient.name_Ingredient %></h3><br>
                         <img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>"/><br>
                         <input type="radio" name="quesoSelected" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados" > <br></center>
                        
                        </div>
                    <% end %>
                  <% end %>
                </div> </center>
                <br><br>
              <div class="row" > 
                <center><h2 style="color:#201C3D;">Verduras</h2></center>
                <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %> 
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==6) %>
                        <div class="col-md-3">
                        <center><h3><%= ingredient.name_Ingredient %></h3>
                        <img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>"/><br>
                        <input type="checkbox" name="ingredients[]" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados"><br></center><br><br>
                        </div>
                    <% end %>
                  <% end %>
                </div>
              <div class="row" > 
                 <center><h2 style="color:#201C3D;">Salsas</h2></center>
                <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %> 
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==7) %>
                        <div class="col-md-3">
                        <center><h3><%= ingredient.name_Ingredient %></h3>
                        <img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>" size="80x80"/><br>
                        <input type="checkbox" name="ingredients[]" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados"><br></center><br><br>
                        </div>
                    <% end %>
                  <% end %>
                </div>
              <div class="row" > 
                 <center><h2 style="color:#201C3D;">Aderezos</h2></center>
                <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %> 
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==8) %>
                        <div class="col-md-3">
                        <center><h3><%= ingredient.name_Ingredient %></h3>
                        <img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>" size="80x80"/><br>
                        <input type="checkbox" name="ingredients[]" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados"><br></center><br><br>
                        </div>
                    <% end %>
                  <% end %>
                </div>
              <div class="row" > 
                 <center><h2 style="color:#201C3D;">Extras</h2></center>
                <br><br>
                  <% @ingredients = Ingredient.order(:category_id).all
                  @ingredients.each do |ingredient| %> 
                  <% @precio = Ingredient.find(ingredient.id).Price %>
                  <input type="hidden" id="precio_<%=ingredient.id%>" value= <%="#{@precio}" %> />
                    <% if (ingredient.category_id==9) %>
                        <div class="col-md-3">
                        <center><h3><%= ingredient.name_Ingredient %></h3>
                        <img src="<%= ingredient.imageno.url%>" id="imagePanes_<%=ingredient.id %>"/><br>
                        <input type="checkbox" name="ingredients[]" id="ingredients__<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados"><br></center><br>
                        </div>
                    <% end %>
                  <% end %>
                </div>

              </td>
              <td width="89">&nbsp;</td>
            </tr>
            <tr> <td width="155" scope="col">&nbsp;</td></tr>
            <tr> <td width="155" scope="col">&nbsp;</td></tr>
      </tbody>
    </table>
  
  

  <div class="field">
    <%= f.label :hour %>
    <%= f.time_field :hour, :class => "form-control", value: "#{DateTime.now.strftime("%H:%M")}", min:"#{DateTime.now.strftime("%H:%M")}"%>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments, :class => "form-control", :placeholder => "Ingrese comentario"%>
  </div>

  <div class="field">
  <% if current_user %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <% end %>  
  </div>

  <div class="field">
  
    <% tipoSand = Ingredient.find(tipo)
    @tam = 15
    if tipoSand.name_Ingredient.include? "15"
      @tam = 15
    else
      @tam = 30
    end %>
  <input type="hidden" id="precio_Tipo" value= <%="#{tipoSand.Price}" %> />
    <%= f.hidden_field :tamaño, :value => @tam %>
    <%= f.hidden_field :tipo, :value => tipo %>
  </div>

   <div class="field">
    <label>Cantidad: </label>
    <%= f.number_field :quantity, :class => "seleccionados"%>
  </div>

   <div class="field">
    <label>Total: </label> <input placeholder="Seleccione un ingrediente" type="number" value="" name="order[total]" id="order_total" readonly>
    <br>
    <label id="mensaje"></label>
  </div>

 <center>
  <div class="actions" >
  <% if current_user %>
    <%= f.submit :id => "order_submit" %>
  <% end %>  
  </div></center>
      <script type="text/javascript">
      $('.seleccionados').bind('click', function() {
        var chequeados, costo
        chequeados = "";
        costo = 0;
        $("input.seleccionados:checked").each(function(){            
          chequeados = chequeados +" "+ $(this).val();
          costo = costo + parseInt(document.getElementById("precio_"+$(this).val()).value);
        });
        costo = costo + parseInt(document.getElementById("precio_Tipo").value);
        costo = costo * parseInt(document.getElementById("order_quantity").value);
        if (<%= current_user.saldo%> < costo ) {
        //alert("No tienes saldo suficiente");
        document.getElementById("order_submit").hidden=true;
        document.getElementById("mensaje").innerHTML = "No tiene saldo suficiente para realizar esta compra";
        }
        else{document.getElementById("order_submit").hidden=false;
        document.getElementById("mensaje").innerHTML = "";
        }
        document.getElementById("order_total").value = ""+costo;
        return true;
      });
    </script>

<% end %>
</center>

app/views/orders/_tipos.html.erb
<style>
.submit input {
  width: 50%;
  height: 100%;
  padding: 10px 10px;
  background: #201C3D;
  color: #fff;
  display: block;
  border: none;
  margin-top: 20px;
  left: 0;
  bottom: 0;;
  border-bottom-width: 7px;
  font-size:20px;
}

</style> 

<center>
      <table width="1213" border="0" cellspacing="0" cellpadding="0">
      <tbody>
      <tr>
      </tr>
      <th width="155" scope="col">&nbsp;</th>
      <th width="155" scope="col">&nbsp;</th>
      <th width="155" scope="col">&nbsp;</th>
        <tr>
          <td width="190" scope="col">&nbsp;</td>
          <td width="934" scope="col">
                    
          <div class="row no-gutter">
          <center><h1>Sabor Sandwich Tamaño (<%= @sizeSelected %> cm)</h1></center>
              <br><br>
              <% if @sizeSelected=='15'
              tiposSan = Ingredient.where(category_id: '2')
            else                
              tiposSan = Ingredient.where(category_id: '3')
            end 
               %>
              <%= form_tag :action => 'PrimeraEtapa' do %>
              <% tiposSan.each do |ingredient| %>
                  <div class="col-md-2">
                  <% tipo = ingredient.name_Ingredient.split("_") %>
              <center><h3 id="sabor_<%=ingredient.id %>"><%= tipo[0] %></h3><br>
              
                <img src="<%= ingredient.imageno.url%>" id="<%=ingredient.id %>" name="sabor_<%=tipo[1] %>" class="seleccionados_<%= tipo[1]%>"/><br>
                  <input type="radio" name="myform[tipo]" id="myform_tipo_<%=ingredient.id %>" value="<%= ingredient.id%>" class="seleccionados" ><br><br></center><br>
                   </div>
              <% end %>
    <center>
    <div class="submit">
    <%= submit_tag "Continuar" %>
    </div></center>
  
  <% end %>
              

          </div>


          </td>
          <th width="89">&nbsp;</th>
        </tr>
        
      </tbody>
    </table>
    </center>



    </td>
    <td width="89">&nbsp;</td>
  </tr>
  <tr> <td width="155" scope="col">&nbsp;</td></tr>
  <tr> <td width="155" scope="col">&nbsp;</td></tr>
</tbody>
</table>
</td> 
</tr>
</tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Hour</th>
      <th>Comments</th>
      <th>User</th>
      <th>Quantity</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at %></td>
        <td><%= order.hour %></td>
        <td><%= order.comments %></td>
        <td><%= order.user %></td>
        <td><%= order.quantity %></td>
        <td><%= order.total %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<!doctype html>
<html>

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
 <script src="http://bxslider.com/js/jquery.min.js"></script>
    <script src="http://bxslider.com/lib/jquery.bxslider.js"></script>
    <script src="http://bxslider.com/js/rainbow.min.js"></script>
    <script src="http://bxslider.com/js/scripts.js"></script>
    <link rel="stylesheet" href="http://bxslider.com/lib/jquery.bxslider.css" type="text/css" />
    <link rel="stylesheet" href="http://bxslider.com/css/styles.css" type="text/css" />
<title>Untitled Document</title>
</head>
<style>
body {
          background-color: #FFFFFF;
        }
.row.no-gutter [class*='col-']:not(:first-child),
.row.no-gutter [class*='col-']:not(:last-child) {
  padding-right: 0;
  padding-left: 0;

}
</style>
<body>

<table width="100%" border="1" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>
      <td align="center"><table width="50%" border="1" cellspacing="0" cellpadding="0">
          <tbody>
          <tr> </tr>
          </tbody>
        </table>
        <table width="865" border="0" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td width="449" align="center">&nbsp;</td>
              <td width="450" align="center">&nbsp;</td>
            </tr>
          </tbody>
        </table>
        
  
        <table width="1213" border="0" cellpadding="0" cellspacing="0">
	  		<tbody>
	  				<tr> <td width="155" scope="col">&nbsp;</td></tr>
		    		<tr>
			      	<td width="155" scope="col">&nbsp;</td>
			      	<td width="930" scope="col">
			      	
					<th></th><h2>Prepara tu Sandwich a tu gusto!!</h2>
					</td>
					</tr>
			</tbody>
		</table>

		<table width="53%" border="1" cellspacing="0" cellpadding="0">
          <tbody>
          			<tr>
           			 <td align="center"><table border="0" align="center" cellpadding="0" cellspacing="0">
             		 <tbody>
                	<script type="text/javascript">
  					$(document).ready(function(){
    
					$('.bxslider').bxSlider({
  					auto: true,
    				autoControls: false,
					hideControlOnEnd:true
					});
 					 });
            </script>
                <tr>
                  <td width="963" align="right" valign="middle" style="text-align: center"><ul class="bxslider">
                    <li style="color: #FFFFFF"><%= image_tag "op1.png", :width=>"300" %></li>
                    <li><%= image_tag "op4.png", :width=>"300"%></li>
                    <li><%= image_tag "op5.png" %></li>
                    <li><%= image_tag "op2.png" %></li>
                  </ul></td>
                </tr>
              </tbody>
            </table></td>
          </tr>
        </tbody>
  		</table>

  			<table width="1213" border="0" cellpadding="0" cellspacing="0">
	  		<tbody>
	  				<tr> <td width="155" scope="col">&nbsp;</td></tr>
	  				<tr> <td width="155" scope="col">&nbsp;</td></tr>
	  				<tr> <td width="155" scope="col">&nbsp;</td></tr>
		    		<tr>
			      	<td width="155" scope="col">&nbsp;</td>
			      	<td width="952" scope="col">
			      	
					
					<div class="row" >
					<th></th><th></th><h2>Paso 1: Tamaño</h2>
					
					<%= form_tag :action => 'opcion' do %>
						<div class="btn-group">
					  	<button type="button" class="btn btn-alert">Tamaño</button>
					  	<button type="button" class="btn btn-alert dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					    <span class="sr-only">Toggle Dropdown</span>
					  	</button>
					  	<div class="dropdown-menu">
					  	<button class="dropdown-item" type="submit" name="myform[opc]" value="15">15 cm</button><br>
					    <button class="dropdown-item" type="submit" name="myform[opc]" value="30">30 cm</button> 
					    </div> 
					    </div>
					    
					<% end %>
				    </div>
					</td>
					</tr>
			</tbody>
		</table>



					
	  </body>	



<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<center>
<br> <br>
<h2 id="notice"><%= notice %></h2>

<h3>
  <strong>Created at:</strong>
  <%= @order.created_at %>
</h3>

<h3>
  <strong>Hour:</strong>
  <%= @order.hour %>
</h3>

<h3>
  <strong>Comments:</strong>
  <%= @order.comments %>
</h3>

<h3>
  <strong>User:</strong>
  <%= @order.user %>
</h3>

<h3>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</h3>

<h3>
  <strong>Total:</strong>
  <%= @order.total %>
</h3>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
</center>